// Generated by scripts/gen-theta-assets.py. Do not edit by hand.
export const THETA_RING =
  "M23 3h1v1h-1zM18 4h11v1h-11zM15 5h6v1h-6zM26 5h5v1h-5zM14 6h4v1h-4zM29 6h4v1h-4zM12 7h4v1h-4zM31 7h3v1h-3zM11 8h3v1h-3zM33 8h2v1h-2zM11 9h2v1h-2zM34 9h2v1h-2zM10 10h2v1h-2zM35 10h2v2h-2zM9 11h3v1h-3zM9 12h2v1h-2zM36 12h2v1h-2zM8 13h2v2h-2zM37 13h1v1h-1zM37 14h2v1h-2zM7 15h3v1h-3zM38 15h1v1h-1zM7 16h2v3h-2zM38 16h2v2h-2zM39 18h1v2h-1zM6 19h3v3h-3zM39 20h2v11h-2zM6 22h2v2h-2zM6 24h3v3h-3zM7 27h2v3h-2zM7 30h3v1h-3zM8 31h2v2h-2zM39 31h1v1h-1zM38 32h2v2h-2zM8 33h3v1h-3zM9 34h2v1h-2zM37 34h2v2h-2zM9 35h3v1h-3zM10 36h3v1h-3zM36 36h2v2h-2zM11 37h2v1h-2zM11 38h3v1h-3zM35 38h2v1h-2zM12 39h3v1h-3zM34 39h2v1h-2zM13 40h4v1h-4zM32 40h3v1h-3zM14 41h5v1h-5zM31 41h3v1h-3zM16 42h6v1h-6zM27 42h5v1h-5zM18 43h12v1h-12z";
export const THETA_WAVE =
  "M42 18h3v1h-3zM41 19h3v1h-3zM39 20h3v1h-3zM13 21h6v1h-6zM37 21h3v1h-3zM10 22h12v1h-12zM35 22h4v1h-4zM8 23h4v1h-4zM20 23h5v1h-5zM31 23h5v1h-5zM7 24h3v1h-3zM23 24h10v1h-10zM6 25h2v1h-2zM5 26h2v1h-2zM4 27h2v1h-2zM3 28h2v1h-2z";
export const THETA_GRID = 48;

// Coarser cut for the small UI mark. A 48 grid drawn at ~24px puts
// two logo pixels in one device pixel and reads as a blurry ring.
export const THETA_SMALL =
  "M8 2h7v1h-7zM6 3h2v1h-2zM15 3h2v1h-2zM5 4h2v1h-2zM17 4h1v1h-1zM5 5h1v1h-1zM17 5h2v1h-2zM4 6h1v2h-1zM18 6h1v1h-1zM19 7h1v3h-1zM3 8h2v1h-2zM3 9h1v3h-1zM19 10h2v1h-2zM5 11h7v1h-7zM16 11h3v1h-3zM20 11h1v3h-1zM3 12h2v1h-2zM12 12h4v1h-4zM3 13h1v1h-1zM3 14h2v1h-2zM19 14h1v4h-1zM4 15h1v2h-1zM4 17h2v1h-2zM5 18h2v1h-2zM6 19h1v1h-1zM7 20h2v1h-2zM8 21h8v1h-8z";
export const THETA_SMALL_GRID = 24;
