#!/usr/bin/env python3
"""Generate the pixelated theta paths the background renders.

The mark is the original theta vector quantised onto a 48 pixel grid, so the
shape stays identical to the brand mark while reading as pixel art. Run after
changing the geometry or the ring weight below:

    python3 scripts/gen-theta-path.py

Writes src/components/thetaPath.ts.
"""
import math, pathlib
from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parent.parent
GRID = 48

# Source geometry, taken verbatim from the pre-pixel vector.
OUTER = [(0,-140),(70,-140),(115,-85),(118,-5),(121,75),(78,138),(5,142),
         (-70,145),(-118,88),(-120,5),(-122,-78),(-75,-138),(-2,-141)]
INNER = [(-4,-120),(-62,-116),(-100,-65),(-98,5),(-96,72),(-58,122),(4,122),
         (64,122),(100,70),(100,0),(100,-70),(60,-120),(0,-120)]
WAVE  = [(-138,18),(-100,-22),(-55,-28),(-15,-6),(25,16),(75,14),(142,-22)]
ROT   = -6.0

# Ring weight. Scaling the inner contour outwards thins the ring; 1.0 and 14
# are the original solid mark's weights.
INNER_SCALE, WAVE_W = 1.075, 10

def _bez(p0, p1, p2, p3, n=40):
    for i in range(n + 1):
        t = i / n; u = 1 - t
        yield (u*u*u*p0[0] + 3*u*u*t*p1[0] + 3*u*t*t*p2[0] + t*t*t*p3[0],
               u*u*u*p0[1] + 3*u*u*t*p1[1] + 3*u*t*t*p2[1] + t*t*t*p3[1])

def _flatten(pts, close=True):
    out = [pts[0]]; cur = pts[0]; i = 1
    while i + 2 <= len(pts) - 1:
        out.extend(list(_bez(cur, pts[i], pts[i+1], pts[i+2]))[1:])
        cur = pts[i+2]; i += 3
    if close:
        out.append(pts[0])
    return out

def _rot(pts, deg):
    a = math.radians(deg); c, s = math.cos(a), math.sin(a)
    return [(x*c - y*s, x*s + y*c) for x, y in pts]

def bits(part, grid=GRID, ss=16, pad=0.06, thr=0.42):
    """Quantise one half of the mark onto a grid x grid boolean pixel map.

    Ring and wave are quantised apart so they can ship as separate paths and
    be themed independently, but both are measured against the whole mark's
    bounding box, so the halves stay registered with each other.
    """
    outer = _rot(_flatten(OUTER), ROT)
    inner = _rot(_flatten([(x*INNER_SCALE, y*INNER_SCALE) for x, y in INNER]), ROT)
    wave  = _rot(_flatten(WAVE, close=False), ROT)

    pts = outer + inner + wave; r = WAVE_W / 2
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    x0, x1, y0, y1 = min(xs) - r, max(xs) + r, min(ys) - r, max(ys) + r
    span = max(x1 - x0, y1 - y0) / (1 - 2 * pad)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2

    N = grid * ss; sc = N / span
    T = lambda p: ((p[0] - cx) * sc + N/2, (p[1] - cy) * sc + N/2)

    im = Image.new("L", (N, N), 0); d = ImageDraw.Draw(im)
    if part == "ring":
        d.polygon([T(p) for p in outer], fill=255)
        d.polygon([T(p) for p in inner], fill=0)       # ring hole
    else:
        wp = [T(p) for p in wave]
        d.line(wp, fill=255, width=max(1, round(WAVE_W * sc)), joint="curve")
        rr = WAVE_W * sc / 2                           # round caps
        for p in (wp[0], wp[-1]):
            d.ellipse([p[0]-rr, p[1]-rr, p[0]+rr, p[1]+rr], fill=255)

    px = im.resize((grid, grid), Image.BOX).load()     # box filter = coverage
    b = [[px[x, y] / 255 >= thr for x in range(grid)] for y in range(grid)]

    # Drop pixels with no orthogonal neighbour: the curve occasionally throws
    # off a single detached dot that reads as dirt rather than as the mark.
    return [[b[y][x] and any(b[y+dy][x+dx] for dx, dy in ((1,0),(-1,0),(0,1),(0,-1))
                             if 0 <= x+dx < grid and 0 <= y+dy < grid)
             for x in range(grid)] for y in range(grid)]

def to_path(bits):
    """Merge the pixel map into as few axis-aligned rects as possible."""
    g = len(bits); grid = [row[:] for row in bits]; rects = []
    for y in range(g):
        x = 0
        while x < g:
            if not grid[y][x]:
                x += 1; continue
            w = 0
            while x + w < g and grid[y][x + w]:
                w += 1
            h = 1                                      # grow down while the run matches
            while y + h < g and all(grid[y+h][x:x+w]) and \
                  (x == 0 or not grid[y+h][x-1]) and (x+w == g or not grid[y+h][x+w]):
                h += 1
            for yy in range(y, y + h):
                grid[yy][x:x+w] = [False] * w
            rects.append((x, y, w, h)); x += w
    return "".join(f"M{x} {y}h{w}v{h}h-{w}z" for x, y, w, h in rects)

if __name__ == "__main__":
    out = ROOT / "src/components/thetaPath.ts"
    out.write_text(
        "// Generated by scripts/gen-theta-path.py. Do not edit by hand.\n"
        f'export const THETA_RING =\n  "{to_path(bits("ring"))}";\n'
        f'export const THETA_WAVE =\n  "{to_path(bits("wave"))}";\n'
        f"export const THETA_GRID = {GRID};\n")
    print("wrote", out.relative_to(ROOT))
